DROP TABLE ELECAUDITHEADER CASCADE CONSTRAINTS;

CREATE TABLE ELECAUDITHEADER
(
  AUDITYEAR                 VARCHAR2(4 BYTE),
  REPORTID                  NUMBER(12),
  FYENDDATE                 DATE,
  AUDITTYPE                 VARCHAR2(1 BYTE),
  PERIODCOVERED             VARCHAR2(1 BYTE),
  NUMBERMONTHS              NUMBER(2),
  MULTIPLEEINS              VARCHAR2(1 BYTE),
  EIN                       VARCHAR2(9 BYTE),
  AUDITEENAME               VARCHAR2(70 BYTE),
  STREET1                   VARCHAR2(45 BYTE),
  STREET2                   VARCHAR2(45 BYTE),
  CITY                      VARCHAR2(30 BYTE),
  STATE                     VARCHAR2(2 BYTE),
  ZIPCODE                   VARCHAR2(9 BYTE),
  AUDITEECONTACT            VARCHAR2(50 BYTE),
  AUDITEETITLE              VARCHAR2(40 BYTE),
  AUDITEEPHONE              VARCHAR2(10 BYTE),
  AUDITEEFAX                VARCHAR2(10 BYTE),
  AUDITEEEMAIL              VARCHAR2(60 BYTE),
  AUDITEEDATESIGNED         DATE,
  AUDITEENAMETITLE          VARCHAR2(70 BYTE),
  CPAFIRMNAME               VARCHAR2(64 BYTE),
  CPASTREET1                VARCHAR2(45 BYTE),
  CPASTREET2                VARCHAR2(45 BYTE),
  CPACITY                   VARCHAR2(30 BYTE),
  CPASTATE                  VARCHAR2(2 BYTE),
  CPAZIPCODE                VARCHAR2(9 BYTE),
  CPACONTACT                VARCHAR2(50 BYTE),
  CPATITLE                  VARCHAR2(40 BYTE),
  CPAPHONE                  VARCHAR2(10 BYTE),
  CPAFAX                    VARCHAR2(10 BYTE),
  CPAEMAIL                  VARCHAR2(60 BYTE),
  CPADATESIGNED             DATE,
  COGOVER                   VARCHAR2(1 BYTE),
  COGAGENCY                 VARCHAR2(2 BYTE),
  TYPEREPORT_FS             VARCHAR2(4 BYTE),
  REPORTABLECONDITION       VARCHAR2(1 BYTE),
  MATERIALWEAKNESS          VARCHAR2(1 BYTE),
  MATERIALNONCOMPLIANCE     VARCHAR2(1 BYTE),
  GOINGCONCERN              VARCHAR2(1 BYTE),
  TYPEREPORT_MP             VARCHAR2(4 BYTE),
  DOLLARTHRESHOLD           NUMBER(12),
  LOWRISK                   VARCHAR2(1 BYTE),
  REPORTREQUIRED            VARCHAR2(1 BYTE),
  TOTFEDEXPEND              NUMBER(12),
  DATEMODIFIED              DATE,
  AUDITDAY                  VARCHAR2(2 BYTE),
  AUDITMONTH                VARCHAR2(2 BYTE),
  FINAL                     VARCHAR2(1 BYTE),
  COPIES                    VARCHAR2(2 BYTE),
  REPORTABLECONDITION_MP    VARCHAR2(1 BYTE),
  MATERIALWEAKNESS_MP       VARCHAR2(4 BYTE),
  QCOSTS                    VARCHAR2(1 BYTE),
  CYFINDINGS                VARCHAR2(1 BYTE),
  PYSCHEDULE                VARCHAR2(1 BYTE),
  DUP_REPORTS               VARCHAR2(1 BYTE),
  COG_AGENCY                VARCHAR2(2 BYTE),
  MULTIPLEDUNS              VARCHAR2(1 BYTE),
  DUNS                      VARCHAR2(9 BYTE),
  VERSION                   NUMBER(2),
  REVISION                  VARCHAR2(1 BYTE),
  AUDITEECERTIFYNAME        VARCHAR2(50 BYTE),
  AUDITEECERTIFYTITLE       VARCHAR2(50 BYTE),
  SIGNIFICANTDEFICIENCY     VARCHAR2(1 BYTE),
  SD_MATERIALWEAKNESS       VARCHAR2(1 BYTE),
  SIGNIFICANTDEFICIENCY_MP  VARCHAR2(1 BYTE),
  SD_MATERIALWEAKNESS_MP    VARCHAR2(1 BYTE),
  AUDITEE_SIG_CODE          NUMBER(12),
  AUDITOR_SIG_CODE          NUMBER(12),
  MULTIPLE_CPAS             VARCHAR2(1 BYTE),
  CPA_IDES_EMAIL            VARCHAR2(60 BYTE),
  AUDITEE_IDES_EMAIL        VARCHAR2(60 BYTE),
  AUDITOR_EIN               VARCHAR2(9 BYTE),
  ELECAUDITHEADERID         NUMBER
)
TABLESPACE TS_SAP
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ELECAUDITHEADER_IND ON ELECAUDITHEADER
(AUDITYEAR, REPORTID, VERSION)
LOGGING
TABLESPACE TS_SAP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



