DROP TABLE ELECAUDITS CASCADE CONSTRAINTS;

CREATE TABLE ELECAUDITS
(
AUDITYEAR VARCHAR2(4 BYTE),
REPORTID NUMBER(12),
CFDASEQNUM NUMBER(7),
CFDA VARCHAR2(50 BYTE),
FEDERALPROGRAMNAME VARCHAR2(74 BYTE),
AMOUNT NUMBER(12),
MAJORPROGRAM VARCHAR2(4 BYTE),
TYPEREQUIREMENT VARCHAR2(15 BYTE),
QCOSTS VARCHAR2(12 BYTE),
FINDINGS VARCHAR2(3 BYTE),
FINDINGREFNUMS VARCHAR2(100 BYTE),
PASS_FLAG VARCHAR2(1 BYTE),
FINAL VARCHAR2(1 BYTE),
RD VARCHAR2(4 BYTE),
DIRECT VARCHAR2(4 BYTE),
CFDA_PREFIX VARCHAR2(2 BYTE),
CFDA_EXT VARCHAR2(50 BYTE),
EIN VARCHAR2(9 BYTE),
DUNS VARCHAR2(9 BYTE),
TYPEREPORT_MP VARCHAR2(1 BYTE),
VERSION NUMBER(2),
ARRA VARCHAR2(4 BYTE),
LOANS VARCHAR2(4 BYTE),
ELECAUDITSID NUMBER,
FINDINGSCOUNT INTEGER
)
TABLESPACE TS_SAP
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
INITIAL 64K
NEXT 1M
MINEXTENTS 1
MAXEXTENTS UNLIMITED
PCTINCREASE 0
BUFFER_POOL DEFAULT
FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT
)
NOLOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ELECAUDITS_IND ON ELECAUDITS
(AUDITYEAR, REPORTID, CFDASEQNUM, VERSION)
LOGGING
TABLESPACE TS_SAP
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
INITIAL 64K
NEXT 1M
MINEXTENTS 1
MAXEXTENTS UNLIMITED
PCTINCREASE 0
BUFFER_POOL DEFAULT
FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT
)
NOPARALLEL;


