DROP TABLE ELECCOMPONENTS CASCADE CONSTRAINTS;

CREATE TABLE ELECCOMPONENTS
(
FINANCIAL_STATEMENTS VARCHAR2(25 BYTE),
SEFA VARCHAR2(25 BYTE),
SCHEDULE_PRIOR_AUDIT_FINDINGS VARCHAR2(25 BYTE),
OPINION_FS VARCHAR2(25 BYTE),
REPORT_INTERNAL_CONTROL VARCHAR2(25 BYTE),
GASREPORT_ON_COMPLIANCE VARCHAR2(25 BYTE),
SFQC VARCHAR2(25 BYTE),
CAP VARCHAR2(25 BYTE),
OPINION_OR_DISCLAIMER_SFA VARCHAR2(25 BYTE),
REPORTID NUMBER(12),
VERSION NUMBER(2),
GASREPORT_INTERNAL_CONTROL VARCHAR2(25 BYTE),
REPORT_ON_COMPLIANCE VARCHAR2(25 BYTE),
AUDITYEAR VARCHAR2(4 BYTE),
ELECCOMPONENTSID NUMBER
)
TABLESPACE TS_SAP
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
INITIAL 64K
NEXT 1M
MINEXTENTS 1
MAXEXTENTS UNLIMITED
PCTINCREASE 0
BUFFER_POOL DEFAULT
FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT
)
NOLOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


